# Generated by Django 6.0.3 on 2026-06-07 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcodeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predata',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_data', to='testcodeapp.category'),
        ),
        migrations.AlterField(
            model_name='predata',
            name='mgm_code',
            field=models.CharField(default='mgm#', max_length=100),
        ),
        migrations.AlterField(
            model_name='predata',
            name='status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Not Normal', 'Not Normal')], default='Not Normal', max_length=50),
        ),
    ]
