# Generated by Django 6.0.3 on 2026-06-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcodeapp', '0002_alter_predata_category_alter_predata_mgm_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predata',
            name='mgm_code',
            field=models.CharField(default='mgm#', max_length=100, unique=True),
        ),
    ]
